version: '2'
services:
 haproxy:
   image: m21lab/haproxy:1.6.2
   links:
     - letsencrypt
   volumes_from:
     - letsencrypt
 letsencrypt:
   image: m21lab/letsencrypt:1.0
   environment:
     DOMAINS: 'dev2.eagerduck.com'
     EMAIL: 'david@eagerduck.com'
     LOAD_BALANCER_SERVICE_NAME: 'haproxy'
     OPTIONS: '--staging'
 registry:
   volumes_from:
     - letsencrypt:ro
   environment:
     REGISTRY_HTTP_SECRET: "your-http-secret"
     REGISTRY_HTTP_TLS_CERTIFICATE: /etc/letsencrypt/live/dev2.eagerduck.com/fullchain.pem
     REGISTRY_HTTP_TLS_KEY: /etc/letsencrypt/live/dev2.eagerduck.com/privkey.pem
 registry-ui:
   environment:
     FORCE_SSL: 'true'
     ENV_REGISTRY_PROXY_FQDN: 'dev2.eagerduck.com'
     ENV_DOCKER_REGISTRY_USE_SSL: 1
